# CrateKeys configuration (created by SavionLegendZzz)
---
Crate: 19
# CrateKeys block (please use IDs)

CrateKey-Item: 341
# CrateKey item

failed: "You need a crate key to open the crate."
# CrateKey failed message

completed: "Items were added to your inventory!"
# CrateKey completed message

ID-1: 0
ID-2: 255
# The items go from 0 to 255 by ID.

number-of-items: 1
# How many of a certain item you would get.
...
